sudo: required
language: java
jdk: openjdk8

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

install: true
script:
  - mvn clean install -DskipTests=true -B

cache:
  directories:
    - $HOME/.m2

after_success:
  - docker login -u digodiego -p @mesma1012
  - export IMAGE_NAME=digodiego/api-revenda
  - docker build -t $IMAGE_NAME:$COMMIT -t $IMAGE_NAME:latest .
  - docker push $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:$COMMIT