version: "3.7"

services:

  api:
    image: digodiego/api-revenda:v00.00.01
    ports:
      - 9000:9000
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/revendas
      DATABASE_USER: postgres
      DATABASE_PASSWORD: controlRevendas
    depends_on:
      - db
    networks:
      - api-network
  db:
    image: postgres:10-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: revendas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: controlRevendas
    networks:
      - api-network

networks:
  api-network: