version: "3.7"

services:

  web:
    image: digodiego/web-revenda
    ports:
      - 80:80
    restart: always
    depends_on:
      - api
    networks:
      - api-network
  api:
    image: digodiego/api-revenda
    ports:
      - 9000:8080
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/revendas
      DATABASE_USER: postgres
      DATABASE_PASSWORD: controlRevendas
    depends_on:
      - db
    networks:
      - api-network
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - 5439:5432
    environment:
      POSTGRES_DB: revendas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: controlRevendas
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - api-network

volumes:
  database_data:
    driver: local

networks:
  api-network: