---
version: "3.7"
services:
  db:
    image: "postgres:9.6-alpine"
    restart: "always"
    ports:
    - "5432:5432"
    volumes:
    - "database_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "control"
      POSTGRES_DB: "portal-2016"
    networks:
    - "portal"
  fila:
    image: "webcenter/activemq"
    restart: "always"
    ports:
    - "8161:8161"
    - "61616:61616"
    volumes:
    - "activemq_db:/var/log/activemq"
    environment:
    - "ACTIVEMQ_MIN_MEMORY=512"
    - "ACTIVEMQ_MAX_MEMORY=2048"
    - "ACTIVEMQ_ENABLED_AUTH=false"
    - "ACTIVEMQ_ADMIN_LOGIN=admin"
    - "ACTIVEMQ_ADMIN_PASSWORD=admin"
    networks:
    - "portal"
  portal-web:
    image: "linkedby/portal-web"
    restart: "always"
    ports:
    - "80:80"
    networks:
    - "portal"
    depends_on:
    - "portal-api"
  portal-api:
    image: "linkedby/portal-api-local:v1.00.01"
    restart: "always"
    ports:
    - "9000:8080"
    environment:
      DATABSE_PASSWORD: "control"
      DATABASE_URL: "jdbc:postgresql://db:5432/portal-2016?reWriteBatchedInserts=true"
      PORT: "9000"
      ACTIVEMQ: "tcp://fila:61616"
      DATABASE_USER: "postgres"
    networks:
    - "portal"
    depends_on:
    - "db"
    - "fila"
volumes:
  activemq_db:
    driver: "local"
  database_data:
    driver: "local"
networks:
  portal:
    driver: "bridge"
